const USER_RESULT_CODES = {
    NICKNAME_SAVE_SUCCESS: "NICKNAME_SAVE_SUCCESS",
    NICKNAME_SAVE_DUPLICATE: "NICKNAME_SAVE_DUPLICATE",
    NICKNAME_SAVE_LIMIT_EXCEEDED: "NICKNAME_SAVE_LIMIT_EXCEEDED",
    NICKNAME_DELETE_SUCCESS: "NICKNAME_DELETE_SUCCESS",
};

module.exports = USER_RESULT_CODES;