const ERROR_KEY = {
    INVALID_RIOT_TAG_FORMAT: 'INVALID_RIOT_TAG_FORMAT',
    INVALID_STEAM_PROFILE_LINK: 'INVALID_STEAM_PROFILE_LINK',
    UNKNOWN_MENU_SELECTION: 'UNKNOWN_MENU_SELECTION',
    GUILD_UPDATE_FAILED: 'GUILD_UPDATE_FAILED',
}

module.exports = ERROR_KEY;