const STATE_KEYS = {
    NO_USER_DATA: 'NO_USER_DATA',
    NO_NICKNAMES: 'NO_NICKNAMES',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAIL: 'DELETE_FAIL',
    NICKNAME_SAVE_SUCCESS: 'NICKNAME_SAVE_SUCCESS',
    NICKNAME_SAVE_LIMIT_EXCEEDED: 'NICKNAME_SAVE_LIMIT_EXCEEDED',
    NICKNAME_SAVE_DUPLICATE: 'NICKNAME_SAVE_DUPLICATE',
    NICKNAME_DELETE_SUCCESS: 'NICKNAME_DELETE_SUCCESS',
};

module.exports = STATE_KEYS;