const STATE_KEYS = {
    NO_USER_DATA: 'NO_USER_DATA',
    NO_NICKNAMES: 'NO_NICKNAMES',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAIL: 'DELETE_FAIL',
    NICKNAME_SAVE_SUCCESS: 'NICKNAME_SAVE_SUCCESS',
    NICKNAME_SAVE_LIMIT_EXCEEDED: 'NICKNAME_SAVE_LIMIT_EXCEEDED',
    NICKNAME_SAVE_DUPLICATE: 'NICKNAME_SAVE_DUPLICATE',
    NICKNAME_DELETE_SUCCESS: 'NICKNAME_DELETE_SUCCESS',
    NO_ADMIN_PERMISSION: 'NO_ADMIN_PERMISSION',
    NO_MENU_TO_SHOW: 'NO_MENU_TO_SHOW',
    NO_MENU_TO_HIDE: 'NO_MENU_TO_HIDE',
    GUILD_UPDATE_SUCCESS: 'GUILD_UPDATE_SUCCESS'
};

module.exports = STATE_KEYS;