const GUILD_RESULT_CODES = {
    MAIN_CHANNEL_NOT_SET: 'MAIN_CHANNEL_NOT_SET',
    ADMIN_CHANNEL_NOT_SET: 'ADMIN_CHANNEL_NOT_SET',
    GUILD_NOT_FOUND: 'GUILD_NOT_FOUND',
};

module.exports = GUILD_RESULT_CODES;